### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Decending** [markhakansson/klee-tutorial#1]
**_Examples:_**
Get_sign.rs: 
Everything looks good!

Get_sign.c:
A: Show the output, it should look something like this:
KLEE: Using Z3 solver backend
KLEE: done: total instructions = 31
KLEE: done: completed paths = …

C: Regarding the result 255, the expected result for the test is -1 and for an 8 bit integer, taking the 2s complement of 255 results in… -1. It’s possible a typecast from a signed integer to an unsigned integer was made, but what you mention about the return 255 is true still.

Signed 11111111 = -1
Unsigned 11111111 = 255

E: You’re missing an answer at the end.
As for the explainations:
A symbolic variable is created during the generating of tests, it has no value and works with constraints which are added to the variable when the path branches.
A symbolic variable is created during the replaying of the tests, it has the constraints loaded and a value is generated between the constraints so the variable can satisfy the path for the test.

**_Cargo klee examples:_**
get_sign.rs:
Looks good, nothing to change!

cyccnt.rs:
Looks good, nothing to change!

array.rs:
Good explainations!
It’d be handy to have a comment under the [Git commit “A/B/C/D”] where applicable, the error is not explained for example. Now we’re all working on the same lab, so I can see the changes you’ve made to your code, but add the comments for your future coworkers.

**Comment by markhakansson** [comment]
Oh nice, thanks for your feedback :)
