### ISSUE TITLE
Funktionsimplementation

### ISSUE THREAD

**Issue by Decending** [markhakansson/klee-tutorial#2]
Vad jag kan se så har du missat att implementera true / false input för att välja mellan de två olika versionerna av preemption, valet dycker inte upp när jag kör "cargo run -- --help"

Finns det någon specifik anledning till varför du valt att arbeta med floats igenom hela analysen? Jag funderade på samma datatyp tidigt under min implementering, men jag fann inte några fördelar.
Med u32 kommer svaren alltid att avrundas neråt, så i mina divisioner har jag enbart gjort detta fär att hantera avrundningen uppåt:

(Täljare + nämnare - 1) / (nämnare)

Jag misstänker att detta även kan spara några klock cykler då vi slipper kalla på funktionen .ceil()

**Comment by markhakansson** [comment]
Tack för din feedback!

Approximation är en flag till `generate` så man får skriva `generate -a`. Uppdaterade README:n då det var otydligt.

Har använt floats när det är division för säkerhets skull. Men inte tänkt så mycket mer på det. Tror ett par extra cykler på datorn inte gör så mycket i slutändan, så länge det inte körs på någon embedded hardware. Men bra observation.
