### ISSUE TITLE
Resultatpresentation

### ISSUE THREAD

**Issue by Decending** [markhakansson/klee-tutorial#3]
Vi har använt olika verktyg för att bygga vår presentation.
   Jag har använt handlebars i min implementation, medans du har använt askama. Din lösning verkar smidigare nu när jag kollar över den. Du slipper göra många steg som jag behövde implementera, med min helper och din formatering är enklare att förstå sig på också.
   Finns det någon funktionsmässig anledning till varför du har din template i en separat mapp?
   
Bra jobbat!

**Comment by markhakansson** [comment]
Tänkte köra handlebars först men Askama var mindre bloat och enklare att använda så körde med det! Templates brukar väl ligga utanför source code tror jag iaf för EJS och sådant. Askama hade det i sin guide i alla fall!

**Comment by Decending** [comment]
Jag är inte så van vid att arbeta med att generera html, så tänkte jag ställer frågan utifall att det finns någon anledning utanför organisering, om man tänker sig ett stort projekt så är det naturligtvis bättre att ha en separat mapp. Du har rätt att det blir mindre bloat med askama.
