### ISSUE TITLE
General feedback (grade 3-4)

### ISSUE THREAD

**Issue by Decending** [markhakansson/klee-tutorial#4]
Under grade 3 finns det två små gömda frågor jag inte kan hitta svar till:

1.    "Ask yourself, what is the consequence of C(t) > A(t)?"

2.    "Ask yourself, what is the consequence of Ltot > 1?"

Generellt så behöver du nog städa lite bland filerna, va så konsekvent du kan med din design. Common bör du dela upp i de andra filerna på lämpligt sätt, blocking bör finnas med i analysis, etc.

**Comment by markhakansson** [comment]
Tack för feedback!

Jo, men tror inte de frågorna var en del av hemtentan iom
```
Grading:
3. Implement the response time analysis, and overall schedulability test. (Skeleton found under srp_analysis.)
```
Kan hålla med om att det inte är välstädat men lade inte ner så mycket tid på att göra det snyggt.
